'use strict';

/**
 * CAHCards — Card data for Cards Against Humanity.
 * Two packs: pg13 (family-friendly) and adult (original-style).
 * Black cards have { text, pick } where pick = number of white cards needed.
 * White cards are plain strings.
 */

const pg13 = {
  black: [
    { text: "What's the next big trend on social media? _.", pick: 1 },
    { text: "I can't believe our teacher brought _ to class.", pick: 1 },
    { text: "When I grow up, I want to be _.", pick: 1 },
    { text: "The secret ingredient in grandma's cookies is _.", pick: 1 },
    { text: "Nothing ruins a birthday party like _.", pick: 1 },
    { text: "My parents were shocked when they found _ in my room.", pick: 1 },
    { text: "The museum's newest exhibit is dedicated to _.", pick: 1 },
    { text: "Step 1: _. Step 2: _. Step 3: Profit.", pick: 2 },
    { text: "Instead of homework, I turned in _.", pick: 1 },
    { text: "The school talent show was ruined by _.", pick: 1 },
    { text: "Scientists have discovered that _ is the key to happiness.", pick: 1 },
    { text: "My imaginary friend is actually _.", pick: 1 },
    { text: "The worst thing to find in your lunchbox is _.", pick: 1 },
    { text: "In the year 3000, humans will worship _.", pick: 1 },
    { text: "The new national holiday celebrates _.", pick: 1 },
    { text: "My autobiography would be titled '_'.", pick: 1 },
    { text: "The principal announced over the intercom: '_!'", pick: 1 },
    { text: "I got detention for _.", pick: 1 },
    { text: "The pizza delivery guy was surprised to see _.", pick: 1 },
    { text: "NASA's next mission is to send _ to space.", pick: 1 },
    { text: "The substitute teacher introduced herself with _.", pick: 1 },
    { text: "What's hiding under the bed? _.", pick: 1 },
    { text: "_ + _ = A really bad idea.", pick: 2 },
    { text: "My pet's secret talent is _.", pick: 1 },
    { text: "The cafeteria started serving _.", pick: 1 },
    { text: "My New Year's resolution is _.", pick: 1 },
    { text: "Breaking news: _ spotted at the mall!", pick: 1 },
    { text: "The worst superpower would be _.", pick: 1 },
    { text: "Aliens visited Earth and only wanted _.", pick: 1 },
    { text: "My first day at camp was ruined by _.", pick: 1 },
    { text: "The magic genie granted me _ instead of what I wished for.", pick: 1 },
    { text: "What I really want for my birthday is _.", pick: 1 },
    { text: "The school mascot was replaced by _.", pick: 1 },
    { text: "When the power went out, we discovered _.", pick: 1 },
    { text: "The theme park's newest ride is based on _.", pick: 1 },
    { text: "Grandpa won't stop talking about _.", pick: 1 },
    { text: "The class field trip went wrong because of _.", pick: 1 },
    { text: "The number one rule in this house is: no _.", pick: 1 },
    { text: "Instead of a trophy, the winner gets _.", pick: 1 },
    { text: "I accidentally emailed _ to my entire school.", pick: 1 },
    { text: "The new flavor of ice cream is _.", pick: 1 },
    { text: "What did the fortune cookie say? '_.'", pick: 1 },
    { text: "_ is the reason I'm banned from Walmart.", pick: 1 },
    { text: "The worst vacation destination is _.", pick: 1 },
    { text: "I replaced the school flag with _.", pick: 1 },
    { text: "My doctor says I need more _.", pick: 1 },
    { text: "The most embarrassing thing in my search history is _.", pick: 1 },
    { text: "Instead of fireworks, the 4th of July should have _.", pick: 1 },
    { text: "The real reason dinosaurs went extinct was _.", pick: 1 },
    { text: "My dating profile says I'm looking for _.", pick: 1 },
    { text: "The world's worst superhero fights crime with _.", pick: 1 },
    { text: "I built a time machine and brought back _.", pick: 1 },
    { text: "_ is my guilty pleasure.", pick: 1 },
    { text: "The gym teacher made us do _ for exercise.", pick: 1 },
    { text: "If I were president, my first act would be _.", pick: 1 },
    { text: "The school play was about _.", pick: 1 },
    { text: "What keeps me up at night? _.", pick: 1 },
    { text: "The best way to make friends is _.", pick: 1 },
    { text: "I traded my lunch for _.", pick: 1 },
    { text: "Introducing the new Olympic sport: _!", pick: 1 },
    { text: "The bus driver yelled _ and everyone panicked.", pick: 1 },
    { text: "My spirit animal is _.", pick: 1 },
    { text: "The summer camp counselor warned us about _.", pick: 1 },
    { text: "In an alternate universe, _ is currency.", pick: 1 },
    { text: "The dinner table argument was about _.", pick: 1 },
    { text: "Life hack: use _ to solve any problem.", pick: 1 },
    { text: "My yearbook quote will be '_.'", pick: 1 },
    { text: "The vending machine dispensed _ instead of snacks.", pick: 1 },
    { text: "The weirdest thing at the garage sale was _.", pick: 1 },
    { text: "I'm starting a club dedicated to _.", pick: 1 },
    { text: "The school newspaper headline: '_ Strikes Again!'", pick: 1 },
    { text: "My grandma's WiFi password is _.", pick: 1 },
    { text: "_ was surprisingly fun.", pick: 1 },
    { text: "The zoo's newest animal is _.", pick: 1 },
    { text: "My plan to take over the world involves _.", pick: 1 },
    { text: "The dentist found _ in my teeth.", pick: 1 },
    { text: "For show and tell, I brought _.", pick: 1 },
    { text: "When the teacher left the room, we immediately started _.", pick: 1 },
    { text: "The local news reported on _.", pick: 1 },
    { text: "My ringtone is the sound of _.", pick: 1 },
    { text: "What's really inside Area 51? _.", pick: 1 },
    { text: "The family reunion was awkward because of _.", pick: 1 },
    { text: "The treasure map led us to _.", pick: 1 },
    { text: "I challenged my rival to a _ contest.", pick: 1 },
    { text: "The haunted house had _ in every room.", pick: 1 },
    { text: "They said _ would never work. They were right.", pick: 1 },
    { text: "Instead of a pet, I adopted _.", pick: 1 },
    { text: "The movie sequel nobody asked for: _ 2.", pick: 1 },
    { text: "During the fire drill, someone grabbed _.", pick: 1 },
    { text: "_ makes everything better.", pick: 1 },
    { text: "The robot uprising was caused by _.", pick: 1 },
    { text: "My morning routine includes _.", pick: 1 },
    { text: "_ is the reason I failed the test.", pick: 1 },
    { text: "In _ we trust.", pick: 1 },
    { text: "The worst advice I ever received: '_.'", pick: 1 },
    { text: "Make _. Not war.", pick: 1 },
    { text: "For my next trick, I'll need _ and _.", pick: 2 },
    { text: "Before _ there was _.", pick: 2 },
    { text: "Roses are red, violets are blue, _.", pick: 1 },
    { text: "And the award for _ goes to _.", pick: 2 }
  ],
  white: [
    "A really aggressive goose",
    "Accidentally replying all",
    "An army of squirrels",
    "A suspiciously large backpack",
    "Awkward eye contact",
    "Banana peels everywhere",
    "Being picked last for dodgeball",
    "Bubble wrap",
    "A cat wearing a tiny hat",
    "Cheese. Just cheese.",
    "A choir of screaming toddlers",
    "Competitive speed walking",
    "Confusion",
    "Conspiracy theories about pigeons",
    "A conga line at a funeral",
    "Crocs with socks",
    "A dancing inflatable tube man",
    "Dinosaur costumes",
    "A dog driving a car",
    "An endless PowerPoint presentation",
    "Everything from the dollar store",
    "Extreme couponing",
    "Face paint",
    "Fake mustaches",
    "A flash mob",
    "Forgetting everyone's name",
    "Free samples",
    "A friendly ghost",
    "A garage full of rubber ducks",
    "Glitter that never goes away",
    "Going viral for the wrong reasons",
    "A goldfish with a top hat",
    "Grandma's secret recipe",
    "A group of confused tourists",
    "Hiding in a cardboard box",
    "Homework from 2003",
    "Hot dog water",
    "An ice cream truck at midnight",
    "Interpretive dance",
    "Invisible ink",
    "A karate-chopping grandma",
    "Kazoos",
    "Laughing at your own jokes",
    "Leftovers from last week",
    "Licking the bowl clean",
    "Living in a treehouse",
    "A llama in a tuxedo",
    "Losing your shoes at a party",
    "A magician's failed trick",
    "Making weird faces in photos",
    "A marching band",
    "Mismatched socks",
    "A monkey with a keyboard",
    "Napping in public",
    "Ninja moves",
    "An old sandwich",
    "One million rubber bands",
    "Oversized sunglasses",
    "Pajamas in public",
    "A parade of tiny ponies",
    "Passive-aggressive sticky notes",
    "A pillow fort",
    "Pizza for breakfast",
    "Playing air guitar",
    "Potato salad",
    "Pretending to be a robot",
    "A puppy stampede",
    "Questionable life choices",
    "A random act of chaos",
    "Really loud chewing",
    "Riding a shopping cart",
    "A room full of trampolines",
    "Running with scissors",
    "A sandwich that's mostly bread",
    "Screaming into the void",
    "A secret handshake",
    "Shopping cart races",
    "Silly string",
    "Singing in the shower",
    "Sleeping with the lights on",
    "Slipping on a banana peel",
    "Socks and sandals",
    "Someone else's leftovers",
    "Spontaneous karaoke",
    "A squirrel uprising",
    "Standing too close to people",
    "Staring at the microwave",
    "Stepping on a LEGO",
    "A stolen garden gnome",
    "A surprise dance battle",
    "Talking to plants",
    "That one kid who reminds the teacher about homework",
    "Three raccoons in a trench coat",
    "Throwing glitter at problems",
    "A time machine that only goes forward 5 minutes",
    "Too many cats",
    "A trampoline park at 3 AM",
    "Trying to parallel park",
    "An umbrella indoors",
    "Uncomfortable silence",
    "Unexpected confetti",
    "An unreasonably large hat",
    "Using a leaf blower indoors",
    "Velcro shoes",
    "Very aggressive eye contact",
    "Very long fingernails",
    "Walking into a glass door",
    "Wearing a cape to school",
    "Whispering loudly",
    "WiFi going out",
    "A wolf in sheep's clothing",
    "Wrestling with an octopus",
    "Yelling at clouds",
    "Your browser history",
    "Your mom's Facebook posts",
    "Zero situational awareness",
    "A haunted toaster",
    "Aggressive motivational speaking",
    "An avalanche of stuffed animals",
    "Bad karaoke",
    "Befriending a vending machine",
    "Building a fort out of couch cushions",
    "Competitive napping",
    "Dramatically reading the terms and conditions",
    "Eating cereal at midnight",
    "Everyone clapping at the wrong time",
    "Extreme ironing",
    "Finger guns",
    "Getting locked in a bathroom",
    "Googling symptoms at 2 AM",
    "Having strong opinions about fonts",
    "Homework-eating dogs",
    "Intensely folding laundry",
    "Juggling chainsaws",
    "Knitting aggressively",
    "Leaving passive-aggressive reviews",
    "Making eye contact while eating a banana",
    "Narrating your own life",
    "Obsessively organizing things by color",
    "Panic at the disco... literally",
    "Questionable fashion choices",
    "Rearranging the furniture at 3 AM",
    "Sending 47 texts in a row",
    "The entire bee movie script",
    "Turning everything into a competition",
    "Uncomfortable amounts of mayonnaise",
    "Very enthusiastic jazz hands",
    "Wearing sunglasses at night",
    "A yoga pose gone terribly wrong",
    "Zoom call with your camera on by accident",
    "A strongly worded letter",
    "Being trapped in an elevator with a mime",
    "Challenging strangers to thumb wars",
    "Dramatically entering a room",
    "Finding money in old pants",
    "Giving unsolicited life advice",
    "Having the hiccups at the worst time",
    "Introducing yourself with a PowerPoint",
    "Just vibes",
    "Knowing all the words to the national anthem... of another country",
    "Looking both ways and still tripping",
    "Making friendship bracelets for adults",
    "Not knowing how to end a conversation",
    "Opening a bag of chips in a quiet room",
    "Putting googly eyes on everything",
    "Quoting movies in everyday conversation",
    "Running a lemonade stand at age 30",
    "Sneezing with your eyes open",
    "The WiFi password being wrong",
    "Using too many exclamation marks!!!",
    "Vigorously shaking a snow globe",
    "Wearing a birthday hat to work",
    "Yodeling in an elevator",
    "Accidentally starting a cult",
    "Befriending your neighbor's cat",
    "Creating a conspiracy board",
    "Doing the worm at a wedding",
    "Eating soup with a fork",
    "Failing at high-fives",
    "Getting really into birdwatching",
    "Hiding snacks everywhere",
    "Impersonating a traffic cone",
    "Joining every club at school",
    "Keeping score of everything",
    "Living exclusively on chicken nuggets",
    "Making everything a group project",
    "Not understanding how doors work",
    "Overthinking a text message",
    "Photobombing strangers",
    "Quickly changing the subject",
    "Responding to everything with finger guns",
    "Starting a petition for longer weekends",
    "Texting your mom instead of your friend",
    "Uncontrollable laughter at serious moments",
    "Vibing too hard",
    "Wearing crocs to a formal event",
    "Asking the teacher if they've seen a specific meme",
    "Being emotionally attached to a houseplant",
    "Chaotic good energy",
    "Dramatically sighing every five minutes",
    "An existential crisis in aisle 7",
    "Forgetting how old you are",
    "Getting competitive about board games",
    "Having a staring contest with a cat",
    "Ignoring all social cues",
    "Just standing there... menacingly",
    "Knowing way too much about cheese",
    "Loud snoring",
    "Microwaving everything",
    "Never finishing a",
    "Overcommitting to a bit",
    "Practicing karate in the mirror",
    "Realizing you're in the wrong class",
    "Spilling something on yourself immediately",
    "Taking 47 selfies to get one good one",
    "Using air quotes way too much",
    "Voicing your inner monologue out loud",
    "Waving back at someone who wasn't waving at you",
    "Yard sale negotiations",
    "Zoning out during important conversations",
    "An excessively detailed dream journal",
    "Becoming best friends with a crow",
    "Collecting things nobody else wants",
    "Dabbing unironically",
    "Explaining your entire life story to a stranger",
    "Faking an accent for fun",
    "Going to the store for one thing and buying everything else",
    "Having a favorite spoon",
    "Instant regret",
    "Just raw, unfiltered chaos",
    "Kicking a vending machine",
    "Living rent-free in someone's head",
    "Making sound effects for everyday actions",
    "Never learning from mistakes",
    "Openly judging people's grocery carts",
    "Playing dead to avoid responsibilities",
    "Quickly Googling something to win an argument",
    "Riding a Roomba through the house",
    "Saying 'that's what she said' at the worst time",
    "Tripping over absolutely nothing",
    "Understanding nothing but nodding anyway",
    "Very slowly backing away",
    "Winning an argument with yourself",
    "A xylophone at a rock concert",
    "Yelling 'plot twist' at random moments",
    "A zeppelin full of clowns"
  ]
};

const adult = {
  black: [
    { text: "What's that smell? _.", pick: 1 },
    { text: "I drink to forget _.", pick: 1 },
    { text: "What's the worst thing to say on a first date? _.", pick: 1 },
    { text: "I got 99 problems but _ ain't one.", pick: 1 },
    { text: "In a world ravaged by _, our only solace is _.", pick: 2 },
    { text: "What did I bring back from Mexico? _.", pick: 1 },
    { text: "After four drinks, _ seems like a great idea.", pick: 1 },
    { text: "Alternative medicine is now embracing _.", pick: 1 },
    { text: "And the Academy Award for _ goes to _.", pick: 2 },
    { text: "Before I kill you, Mr. Bond, I must show you _.", pick: 1 },
    { text: "_ is a slippery slope that leads to _.", pick: 2 },
    { text: "Coming to Broadway this season, _ The Musical.", pick: 1 },
    { text: "Dude, do not go in that bathroom. There's _ in there.", pick: 1 },
    { text: "During the séance, we made contact with _.", pick: 1 },
    { text: "For my next trick, I will pull _ out of _.", pick: 2 },
    { text: "I never truly lived until I experienced _.", pick: 1 },
    { text: "I'm going to build a theme park called _land!", pick: 1 },
    { text: "I'm sorry, Professor, but I couldn't complete my homework because of _.", pick: 1 },
    { text: "If God didn't want us to enjoy _, he wouldn't have created _.", pick: 2 },
    { text: "In 1,000 years, archaeologists will find _ and think it was _.", pick: 2 },
    { text: "In a shocking twist, the killer was _ all along.", pick: 1 },
    { text: "In his new self-help book, Dr. Phil recommends _.", pick: 1 },
    { text: "In the new Disney movie, the princess falls in love with _.", pick: 1 },
    { text: "Instead of coal, Santa now gives naughty children _.", pick: 1 },
    { text: "It's a pity that kids these days are all getting into _.", pick: 1 },
    { text: "Life for Native Americans was forever changed when the White Man introduced them to _.", pick: 1 },
    { text: "Lifetime presents _, the story of _.", pick: 2 },
    { text: "Maybe she's born with it. Maybe it's _.", pick: 1 },
    { text: "Next from J.K. Rowling: Harry Potter and the Chamber of _.", pick: 1 },
    { text: "Next on ESPN2: The World Series of _.", pick: 1 },
    { text: "Studies show that lab rats navigate mazes 50% faster after being exposed to _.", pick: 1 },
    { text: "The class field trip was completely ruined by _.", pick: 1 },
    { text: "The healing power of _.", pick: 1 },
    { text: "This is the way the world ends. Not with a bang but with _.", pick: 1 },
    { text: "TSA guidelines now prohibit _ on airplanes.", pick: 1 },
    { text: "War! What is it good for? _.", pick: 1 },
    { text: "What are my parents hiding from me? _.", pick: 1 },
    { text: "What ended my last relationship? _.", pick: 1 },
    { text: "What gives me uncontrollable gas? _.", pick: 1 },
    { text: "What is Batman's guilty pleasure? _.", pick: 1 },
    { text: "What will always get you laid? _.", pick: 1 },
    { text: "What will I bring back in time to convince people I am a powerful wizard? _.", pick: 1 },
    { text: "What would grandma find disturbing yet oddly charming? _.", pick: 1 },
    { text: "What's my anti-drug? _.", pick: 1 },
    { text: "What's the crustiest thing in your apartment? _.", pick: 1 },
    { text: "What's the most emo? _.", pick: 1 },
    { text: "What's the new fad diet? _.", pick: 1 },
    { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", pick: 1 },
    { text: "When I am the President of the United States, I will create the Department of _.", pick: 1 },
    { text: "When Pharaoh remained unmoved, Moses called down a plague of _.", pick: 1 },
    { text: "When you get right down to it, _ is just _.", pick: 2 },
    { text: "Why am I sticky? _.", pick: 1 },
    { text: "Why can't I sleep at night? _.", pick: 1 },
    { text: "_ will be the next great trend.", pick: 1 },
    { text: "My country, 'tis of thee, land of _.", pick: 1 },
    { text: "They said we were crazy. They said we couldn't put _ inside of _. They were wrong.", pick: 2 },
    { text: "_ kid tested, mother approved.", pick: 1 },
    { text: "A romantic candlelit dinner would be incomplete without _.", pick: 1 },
    { text: "But before I kill you, Mr. Bond, I must show you _.", pick: 1 },
    { text: "I'm no doctor, but I'm pretty sure what you have is _.", pick: 1 },
    { text: "The blind date was going great until I mentioned _.", pick: 1 },
    { text: "I wish I hadn't lost the instructions for _.", pick: 1 },
    { text: "Here is the church. Here is the steeple. Open the doors and there is _.", pick: 1 },
    { text: "Sorry I'm late, I was busy with _.", pick: 1 },
    { text: "My mom freaked out when she looked at my browser history and found _.", pick: 1 },
    { text: "I went to the Renaissance faire dressed as _.", pick: 1 },
    { text: "That's right, I killed _. How, you ask? _.", pick: 2 },
    { text: "Help me doctor, I've got _ in my butt.", pick: 1 },
    { text: "The new superhero, Captain _, fights crime with _.", pick: 2 },
    { text: "My new workout routine includes _.", pick: 1 },
    { text: "The worst Thanksgiving dish is _.", pick: 1 },
    { text: "In an attempt to reach a wider audience, the museum will now feature _.", pick: 1 },
    { text: "The real reason I got fired was _.", pick: 1 },
    { text: "I went to a party and all I got was _.", pick: 1 },
    { text: "Two things that don't mix: _ and _.", pick: 2 },
    { text: "My safe word is _.", pick: 1 },
    { text: "What's fun until it gets weird? _.", pick: 1 },
    { text: "Forget everything you know about _.", pick: 1 },
    { text: "Don't put _ in your mouth.", pick: 1 },
    { text: "Fun tip: when life gives you lemons, make _.", pick: 1 },
    { text: "The Vegas wedding chapel now offers a _ themed ceremony.", pick: 1 },
    { text: "How am I maintaining my relationship? _.", pick: 1 },
    { text: "Nobody expects _.", pick: 1 },
    { text: "Old MacDonald had _. E-I-E-I-O.", pick: 1 },
    { text: "_ would be woefully incomplete without _.", pick: 2 },
    { text: "The five stages of grief: denial, anger, bargaining, _, acceptance.", pick: 1 },
    { text: "Yo momma is so _ that _.", pick: 2 },
    { text: "I learned the hard way that you can't cheer up a grieving friend with _.", pick: 1 },
    { text: "What left this stain on my couch? _.", pick: 1 },
    { text: "While the United States raced the Soviet Union to the moon, Mexico raced to _.", pick: 1 },
    { text: "I'm not like the rest of you. I'm too busy with _.", pick: 1 },
    { text: "My new startup idea: Uber, but for _.", pick: 1 },
    { text: "The only thing worse than _ is _.", pick: 2 },
    { text: "White people like _.", pick: 1 },
    { text: "What did the US airdrop to the children of Afghanistan? _.", pick: 1 },
    { text: "When the strategy fails, plan B is always _.", pick: 1 },
    { text: "I'm _ and I approve this message.", pick: 1 },
    { text: "Due to budget cuts, the prom theme is _.", pick: 1 },
    { text: "My Netflix and chill turned into _ real quick.", pick: 1 },
    { text: "If _ and _ had a baby, it would be _.", pick: 3 }
  ],
  white: [
    "A balanced breakfast",
    "A bleached whale",
    "A brain tumor",
    "A bucket of fish heads",
    "A clandestine butt scratch",
    "A disappointing birthday party",
    "A foul odor",
    "A gentle caress of the inner thigh",
    "A good sniff",
    "A hot mess",
    "A lifetime of regret",
    "A mating call",
    "A micropig wearing a tiny raincoat",
    "A middle-aged man on roller blades",
    "A mime having a stroke",
    "A monologue from a drunk uncle",
    "A murder most foul",
    "A nuanced take on race relations",
    "A passionate letter to the editor",
    "A pirate's life",
    "A PowerPoint presentation",
    "A really cool hat",
    "A robust mongoloid",
    "A sad handy in the Denny's parking lot",
    "A snapping turtle biting the tip of your junk",
    "A soggy biscuit",
    "A sorority girl with a spray tan",
    "A surprising amount of hair",
    "A team of lawyers",
    "A thermonuclear detonation",
    "A tiny horse",
    "A tray of brownies",
    "A violent sneeze",
    "A web of lies",
    "Absolutely nothing",
    "Accidentally liking a photo from 3 years ago",
    "Active listening",
    "All-you-can-eat shrimp for $4.99",
    "An Applebee's gift card",
    "An awkward pause",
    "An elaborate prank",
    "An existential crisis",
    "An inappropriately timed high five",
    "An unhinged conspiracy theorist",
    "An unresolved childhood trauma",
    "Anxiety",
    "Asking people to be your friend",
    "Authentic frontier gibberish",
    "Bad breath",
    "Being a terrible person",
    "Being on fire",
    "Being passive aggressive",
    "Being rich",
    "Believing in yourself",
    "Blame",
    "Blatant corruption",
    "Bottomless mimosas",
    "Breaking out into song for no reason",
    "Burning man",
    "Butter",
    "Casual racism",
    "Chainsaws for hands",
    "Cheese and crackers",
    "Childhood obesity",
    "Chronic backstabbing disorder",
    "Chunks of dead prostitute",
    "Chutzpah",
    "Coat hanger abortions",
    "Corporate synergy",
    "Cowardice",
    "Crushing debt",
    "Crying into a bag of money",
    "Cultural appropriation",
    "Dad's weird friend",
    "Daddy issues",
    "Dangerously cheesy",
    "Dark and mysterious forces",
    "Dead parents",
    "Deez nuts",
    "Disappointing your father",
    "Doing the right thing",
    "Drinking alone",
    "Dwarf tossing",
    "Eating alone at a restaurant",
    "Emotional baggage",
    "Ethnic cleansing",
    "Everything I know about love",
    "Exactly what you'd expect",
    "Excessive body hair",
    "Expecting a burp and vomiting on the floor",
    "Extreme apathy",
    "Face tattoos",
    "Failing at everything",
    "Fear itself",
    "Feelings",
    "Fiery poops",
    "Finding a spider in your hair",
    "Flirting with disaster",
    "Flying robots that kill people",
    "Free real estate",
    "Full-frontal nudity",
    "Getting naked and watching Cops",
    "Getting out of jury duty",
    "Getting really high",
    "Giving 110%",
    "Going through the whole drive-through in reverse",
    "Good vibes only",
    "Grandma's dentures",
    "Having a strong opinion about Yelp",
    "Holding a grudge",
    "Hoping this all blows over",
    "Horrifying laser hair removal accidents",
    "Hot cheese",
    "Hot people",
    "How bad my feet smell",
    "Human trafficking",
    "Ignoring the problem until it goes away",
    "Inappropriate yodeling",
    "Incest",
    "Insatiable bloodlust",
    "Just the tip",
    "Keeping a straight face",
    "Kids with leashes",
    "Lactation",
    "Land mines",
    "Licking things to claim them as your own",
    "Living in a van down by the river",
    "Lockjaw",
    "Making a scene",
    "Making poor life choices",
    "Man buns",
    "Mansplaining",
    "Meth",
    "Mild inconvenience",
    "Moral ambiguity",
    "Mountain Dew Code Red",
    "Mouth stuff",
    "Multiple stab wounds",
    "My collection of high-tech prostheses",
    "My humps",
    "My inner demons",
    "My relationship status",
    "My sex life",
    "My will to live",
    "Natural male enhancement",
    "Needlessly complicated plans",
    "Nicolas Cage",
    "No pants",
    "Not having a filter",
    "Not showering",
    "Nothing good",
    "Obesity",
    "Object permanence",
    "Obvious favoritism",
    "Old people smell",
    "One thousand tiny crabs",
    "Opposite day",
    "Organ harvesting",
    "Other people's feelings",
    "Overcompensating",
    "Oversharing on social media",
    "Panic",
    "Passive resistance",
    "Peaking in high school",
    "Performance anxiety",
    "Personal space",
    "Poor life choices",
    "Popping the biggest zit ever",
    "Poverty",
    "Pretending to care",
    "Problematic behavior",
    "Pulling out",
    "Punching a dolphin in the face",
    "Questionable ethics",
    "Rage quitting",
    "Really bad gas",
    "Road rage",
    "Saying something stupid",
    "Self-loathing",
    "Selling organs on the black market",
    "Sheer dumb luck",
    "Shopping at Walmart",
    "Showing up uninvited",
    "Shutting up for once",
    "Side effects",
    "Slowly dying inside",
    "Smegma",
    "Some really messed up stuff",
    "Someone who peaked in middle school",
    "Something uncomfortable",
    "Soup that is too hot",
    "Spontaneous combustion",
    "Stress eating",
    "Stuff white people do",
    "Surprise colonoscopy",
    "Sweet sweet revenge",
    "Taco Bell at 2 AM",
    "Tasteful sideboob",
    "Teaching a robot to love",
    "Texting your ex at 3 AM",
    "That weird rash",
    "The American Dream",
    "The audacity",
    "The card you swore you'd never play",
    "The economy",
    "The entire population of Ohio",
    "The entire state of Florida",
    "The friend zone",
    "The inevitability of death",
    "The IRS",
    "The miracle of childbirth",
    "The overwhelming scent of Axe body spray",
    "The patriarchy",
    "The power of friendship",
    "The prostate exam",
    "The sound of silence",
    "The unstoppable march of time",
    "The wrong hole",
    "The wrong kind of attention",
    "Three wishes from a cursed monkey paw",
    "Throwing a party and nobody comes",
    "Too much information",
    "Toxic masculinity",
    "Trophy wives",
    "Trust issues",
    "Trying too hard",
    "Turning a blind eye",
    "Twisting the knife",
    "Two midgets in a trench coat",
    "Uncontrollable sobbing",
    "Unfathomable stupidity",
    "Unresolved tension",
    "Unspoken resentment",
    "Vastly underestimating the situation",
    "Very aggressive hand gestures",
    "Vigorous jazz hands",
    "Violently throwing up",
    "Waiting till marriage",
    "Waking up in a bathtub full of ice",
    "Walking in on your parents",
    "Whatever is making that noise",
    "When keeps it real goes wrong",
    "White knighting",
    "World domination",
    "Worrying about everything",
    "Your weird uncle",
    "Zero chill"
  ]
};

module.exports = { pg13, adult };
